"""empty message

Revision ID: d23f742501b4
Revises: 
Create Date: 2019-12-25 14:28:55.049324+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'd23f742501b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=False),
    sa.Column('slug', sa.Unicode(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_slug'), 'category', ['slug'], unique=True)
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=False),
    sa.Column('thumbnail', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.Unicode(length=1), nullable=False),
    sa.Column('availability', sa.Unicode(length=15), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_availability'), 'book', ['availability'], unique=False)
    op.create_index(op.f('ix_book_category'), 'book', ['category'], unique=False)
    op.create_index(op.f('ix_book_currency'), 'book', ['currency'], unique=False)
    op.create_index(op.f('ix_book_title'), 'book', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_title'), table_name='book')
    op.drop_index(op.f('ix_book_currency'), table_name='book')
    op.drop_index(op.f('ix_book_category'), table_name='book')
    op.drop_index(op.f('ix_book_availability'), table_name='book')
    op.drop_table('book')
    op.drop_index(op.f('ix_category_slug'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
